= Общие сведения об администраторском разделе

Настоящий раздел документации является обобщенной инструкцией по установке системы {dv} 6.

.В данном разделе документации приводится следующая информация:
* Общие требования базовых модулей системы к аппаратному и программному обеспечению.
* Описание установки составляющих систему модулей.
* Общие рекомендации по первоначальной настройке системы.

.Инструкция актуальна для следующих версий модулей {dv}:
* _{mc}_ версии {mc-cu-mc}.
* _{pl}_ версии {pl-cu-mc}.
* _Служба {ws}_ версии {worker-cu-mc}.
* _{bo}_ версии {bo-cu-mc}.
* _{wf}_ версии {wf-cu-mc}.
* _{dm}_ версии {ud-cu-mc}.
* _{ad}_ версии {ad-cu-mc}.
* _{wc}_ версии {wc-cu-mc}.
* _{wincl}_ версии {win-cu-mc}.

Система {dv} имеет модульную архитектуру и предназначена для автоматизации управления документами и бизнес-процессами компании.

.Система включает следующие модули:
* {mc} -- главный инструмент настройки системы
* {pl} -- основное звено модульной структуры {dv}.
+
.{pl} содержит:
** Службу сервера {dv}.
** Компоненты для работы с базами данных.
** Системные карточки _Папки_, _Системные настройки_ и прочие.
** API.
** Базовые сервисы работы с данными (чтение/запись).
** Функции безопасности, поиска и прочие.
+
* Служба {ws} -- обрабатывает задачи, поступившие от других модулей {dv} в фоновом режиме.
* {bo} -- модуль предоставляет:
** Базовые типы карточек: _Задание_, _Группа заданий_, _Документ_.
** Конструкторы для настройки электронного документооборота.
** Справочники, предоставляющие информацию для использования в других карточках.
* {wf} -- содержит службу обработки бизнес-процессов, предоставляет тип карточек _Бизнес-процесс_ и конструктор для настройки БП.
* {dm} -- предоставляет готовое _Приложение_ {dv}, реализующее конкретные прикладные бизнес-сценарии.
* {ad} -- предоставляет типы карточек и бизнес-процессы для организации и выполнения процесса согласования документов.
* {wc} -- предоставляет рабочее место с возможностью работы из браузера с любой машины.
* {wincl} -- предоставляет клиентские программы _{wincl}_ и _Рабочее место администратора_ (РМА), позволяющие выполнять пользовательские, административные и другие операции в системе {dv}.

Все модули, за исключением модуля {pl}, являются зависимыми, т.е. для их работы требуются другие модули. Для модулей могут предоставляться пакеты установки в зависимости от целевой ОС. Если целевая платформа -- ОС семейства Linux, модули поставляются в виде архивов или пакетов, получаемых из репозитория {dv}. Если целевая платформа -- ОС {ms} Windows, пакет поставки может содержать инсталляторы для серверной и клиентской части модулей системы. В некоторых случаях комплект поставки включает только одну часть (как правило, серверную).

.Назначение составляющих комплекта поставки отражено в их названии (бывают исключения):
* Комплект поставки для ОС Linux состоит из архивов вида `имя-модуля_6.1.NNN_deb.zip`, которые содержат:
** Компоненты модуля для установки на сервер {dv} с именами вида `docsvision-platform-**server**_6.1.NNN_all.deb`.
** Необходимые для взаимодействия внутри системы специальные расширения модулей вида `docsvision-**ext-platform-mc**_6.1.NNN_all.deb` (доступны не для всех модулей).
** Также к комплекту _могут_ прилагаться инсталляторы для ОС Windows, например, `{dv} **WindowsClient**.msi` для {wincl} или `{dv} **ResourceKit**.msi` для {rk}.
* Комплект поставки для ОС Windows:
** `{dv} Platform **server**.msi` -- *серверные* компоненты модуля.
** `{dv} EDI **extension for Web-client**` -- необходимые для взаимодействия внутри системы специальные расширения модулей (доступны не для всех модулей).

// О действующих текущих ограничениях можно узнать в разделе "xref:windows-limitations.adoc[]".
